config/routes.rb
StartupSoccerManager::Application.routes.draw do
  resources :clubs
  resources :players
  resources :matches
  
  root to: "matches#index"

end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :founded_at, :name, :club_image_url
  
  has_many :players, order: :last_name
  has_many :host_matches, foreign_key: :host_id
  has_many :guest_matches, foreign_key: :guest_id
  
  validates :name, presence: true, uniqueness: true
  
  def matches
    host_matches + guest_matches
  end
    
  def as_json(options = {})
    super(include: :players)
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :host, class_name: "Club"
  belongs_to :guest, class_name: "Club"

  attr_accessible :guest, :guest_id, :guest_score, :host, :host_id, :host_score, :location, :played_at
  
  def as_json(options = {})
    super(include: [:host, :guest])
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  POSITIONS = {
    "Offense" => {
      "Deep lying forward" => "SS",
      "Centre forward" => "CF",
      "Winger" => "W"
    },
    "Mid-field" => {
      "Defensive midfielder" => "DM",
      "Central midfielder" => "CM",
      "Side midfielder" => "SM",
      "Attacking midfielder" => "AM"
    },
    "Defense" => {
      "Sweeper" => "SW",
      "Center back" => "CB",
      "Full back" => "FB",
      "Wingback" => "WB"
    },
    "Goal" => {
      "Goal Keeper" => "GK"
    },
  }
  
  attr_accessible :acceleration, :aggression, :balance, :born_at, :first_name, :gender, :last_name, :marking, :number, :position, :profile_image_url, :stamina
  attr_accessible :club_id
  
  belongs_to :club
  
  scope :available, where('club_id IS NULL')
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  validates :number, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 99 }
  
  validates :acceleration, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :aggression, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :marking, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :stamina, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  
  def average
    (acceleration + aggression + balance + marking + stamina).to_f / 5
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def as_json(options = {})
    super(include: :club)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  respond_to :html, :json
  
  def index
    @clubs = Club.all
    
    respond_with @clubs
  end
  
  def show
    @club = Club.find(params[:id])
    
    respond_with @club
  end
  
  def new
    @club = Club.new
    
    respond_with @club
  end
  
  def create
    @club = Club.new(params[:club])
    
    if @club.save
      respond_with @club, status: :created
    end
  end
  
  def edit
    @club = Club.find(params[:id])
  
    respond_with @club
  end
  
  def update
    @club = Club.find(params[:id])
    
    if @club.update_attributes params[:club]
      respond_with @club
    end
  end
  
  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    
    respond_with @club
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  respond_to :html, :json
  
  def index
    @matches = Match.order("played_at DESC")
    
    respond_with @matches
  end
  
  def show
    @match = Match.find(params[:id])
    
    respond_with @match
  end
  
  def new
    @match = Match.new
    
    respond_with @match
  end
  
  def create
    @match = Match.new(params[:match])
    
    if @match.save
      respond_with @match
    end
  end
  
  def edit
    @match = Match.find(params[:id])
  end
  
  def update
    @match = Match.find(params[:id])
    
    if @match.update_attributes(params[:match])
      respond_with @match
    end
  end
  
  def destroy
    @match = Match.find(params[:id])
    @match.destroy
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  respond_to :html, :json
  
  def index
    @players = Player.order(:last_name)
    
    respond_with @players
  end
  
  def show
    @player = Player.find(params[:id])
    
    respond_with @player
  end
  
  def new
    @player = Player.new()
    
    respond_with @player
  end
  
  def create
    @player = Player.new(params[:player])
    
    if @player.save
      respond_with @player
    end
  end
  
  def edit
    @player = Player.find(params[:id])
  end
  
  def update
    @player = Player.find(params[:id])
    
    @player.update_attribute :club_id, params[:player][:club_id]
    if @player.update_attributes params[:player]
      respond_with @player
    end
  end
  
  def destroy
    @player = Player.find(params[:id])
    @player.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_controller(controller_name)
    controller.controller_name == controller_name ? "active" : ""
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/clubs/index.html.slim
#clubs

= render "templates/clubs/index"
= render "templates/clubs/club"
= render "templates/clubs/show"
= render "templates/clubs/team"
= render "templates/clubs/team_player"
= render "templates/clubs/edit_team_player"
= render "templates/players/skills"
= render "templates/clubs/new"
= render "templates/clubs/edit"

javascript:
  (function() {
    window.router = new StartupSoccerManager.Routers.ClubsRouter( { clubs: #{@clubs.to_json.html_safe} } );
  })();

app/views/layouts/_navbar.html.slim
.navbar
  .navbar-inner
    = link_to root_path, class: "brand" do
      = t('app.name')
    ul.nav
      li class="#{ active_controller("matches") }" = link_to Match.model_name.human.pluralize, matches_path
      li class="#{ active_controller("clubs")   }" = link_to Club.model_name.human.pluralize, clubs_path
      li class="#{ active_controller("players") }" = link_to Player.model_name.human.pluralize, players_path
    ul.nav.pull-right
      li.divider-vertical
      li.dropdown
        = link_to "#", class: "dropdown-toggle" do
          b.icon-globe
          = "#{t('.languages')} "
          b.caret
        ul.dropdown-menu
          li Example

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t('app.name')
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
body
  .container
    = render "layouts/navbar"
    .content
      = yield
  javascript:
    (function() {
      Backbone.history.start();
    })();

app/views/matches/index.html.slim
#matches

= render "templates/matches/index"
= render "templates/matches/carousel_item"
= render "templates/matches/match"
= render "templates/matches/new"
= render "templates/matches/edit"

javascript:
  (function() {
    window.router = new StartupSoccerManager.Routers.MatchesRouter( { matches: #{@matches.to_json.html_safe} } );
  })();

app/views/players/index.html.slim
#players

= render "templates/players/index"
= render "templates/players/player"
= render "templates/players/show"
= render "templates/players/skills"
= render "templates/players/new"
= render "templates/players/edit"

javascript:
  (function(){
    window.router = new StartupSoccerManager.Routers.PlayersRouter( { players: #{@players.to_json.html_safe} } );
  })();

app/views/templates/clubs/_club.html.slim
script#club_template type="text/template"
  td.clickable
    <%= get("name") %>
  td.clickable
    <%= displayAverage() %>
  td
    .btn-group
      a.btn.btn-small.btn-edit href="#<%= id %>/edit"
        = t('.edit')
      a.btn.btn-small.btn-danger.btn-destroy href="#<%= id %>"
        = t('.destroy')

app/views/templates/clubs/_edit.html.slim
script#edit_club_template type="text/template"
  h1= t('.title')
  
  = render "templates/clubs/form"

app/views/templates/clubs/_edit_team_player.slim
script#club_edit_team_player_template type="text/template"
  .player-name.span2
    <%= formattedName() %>
  .player-position.span1
    strong
      <%= displayPosition() %>
  .actions.span2
    .btn-group
      a.btn.btn-mini.btn-edit
        = t('.edit')
      a.btn.btn-mini.btn-danger.btn-dissociate
        = t('.dissociate')

app/views/templates/clubs/_form.html.slim
.span6
  = form_for :club, html: { class: "soccer-manager-form" } do |f|
    fieldset
      legend
        = t('.legend.logo')
      .control-group
        .club-logo
          img.img-polaroid.clickable src='<%= get("club_image_url") %>'
          span.help-block
            em
              = t('.helpers.club_picture')
    fieldset
      legend
        = t('.legend.basics')
      .control-group
        = f.label :name
        = f.text_field :name, value: "<%= get(\"name\") %>".html_safe
      .control-group
        = f.label :founded_at
        .input-prepend
          span class="add-on"
            b class="icon-calendar"
          = f.text_field :founded_at, class: "datepicker input-small", value: "<%= get(\"founded_at\") %>".html_safe
      .margin-bottom
    fieldset
      legend
        = t('.legend.team')
      .team-players
      .control-group.span4
        = f.label :players
        = f.select :players, Player.available.collect { |p| [p.full_name, p.id] }, { include_blank: true }
        a.btn.btn-success.pull-right.add-player
          = t('.add')
    .form-actions
      = f.submit class: "btn btn-primary"
      = link_to t(".back"), "#", class: "btn"

app/views/templates/clubs/_index.html.slim
script#clubs_template type="text/template"
  h1= t('.title')

  table.table.clubs-table
    thead
      tr
        th.span6
          = Club.human_attribute_name(:name)
        th.span1
          = Club.human_attribute_name(:average)
        th.span1
          = t('.actions')
    tbody
  = link_to t('.new'), "#new", class: "btn btn-primary"

app/views/templates/clubs/_new.html.slim
script#new_club_template type="text/template"
  h1= t('.title')

  = render "templates/clubs/form"

app/views/templates/clubs/_show.html.slim
script#show_club_template type="text/template"
  td colspan="3"
    .club-card-container
      .club-card
        .profile.padded
          .picture
            img class="img-polaroid"
          .name
            strong
              <%= get("name") %>
          .foundation
            <%= foundationYear() %>
        .team.padded
        .player-info-box.padded
          .player-info
            .player-info-header
              .player-picture
                img class="img-polaroid"
              .player-info-content
                .player-info-age
                  span.age
                  = " #{t('common.prompts.age')}"
                .player-info-gender
                  span.gender
                .player-info-number  
                  = "#{t('common.prompts.shirt')} "
                  span.number  
                
            h4= t('.skills')
            .skills
        .field.padded

app/views/templates/clubs/_team.html.slim
script#club_team_template type="text/template"
  <% if (length != 0) { %>
    .first-team
      h4= t('.first_team')
      .players
    .reserve-team
      h4= t('.reserve_team')
      .players
  <% } else { %>
    = t('.no_players')
  <% } %>

app/views/templates/clubs/_team_player.html.slim
script#club_team_player_template type="text/template"
  .player.clickable
    .player-name
      <%= formattedName() %>
    .player-position
      strong
        <%= displayPosition() %>

app/views/templates/matches/_carousel_item.slim
script#matches_carousel_item type="text/template"
  .match-details
    .club.club-right.span3
      img.club-picture src='<%= get("host").get("club_image_url") %>'
      .club-name
        <%= get("host").get("name") %>
    .versus.span4
      <%= get("host_score") %> 
      | X 
      <%= get("guest_score") %>
    .club.club-left.span3
      img.club-picture src='<%= get("guest").get("club_image_url") %>'
      .club-name
        <%= get("guest").get("name") %>

app/views/templates/matches/_edit.html.slim
script#edit_match_template type="text/template"
  h1= t('.title')
  .played-at
    = "#{t('.played_at')}: "
    <%= get("played_at").substring(0, 10) %>
  .span7
    = form_for :match, html: { class: "soccer-manager-form" } do |f|
      fieldset
        legend= t('.set_results')
        .control-group.inline-block.padded-right
          label for="match_host_score"
            <%= get("host").get("name") %> 
          = f.number_field :host_score, class: "input-small", min: 0, value: "<%= get(\"host_score\") %>".html_safe
        i.icon-remove.against-symbol
        .control-group.inline-block.padded-left          
          label for="match_guest_score"
            <%= get("guest").get("name") %> 
          = f.number_field :guest_score, class: "input-small", min: 0, value: "<%= get(\"guest_score\") %>".html_safe
        .form-actions
          = f.submit class: 'btn btn-primary'
          = link_to t('.back'), '#', class: "btn"

app/views/templates/matches/_index.html.slim
script#matches_template type="text/template"
  #matches_carousel.carousel.slide
    .carousel-inner
    a.carousel-control.left href="#matches_carousel" data-slide="prev" &lsaquo;
    a.carousel-control.right href="#matches_carousel" data-slide="next" &rsaquo;
    
  h1= t('.title')
  
  table.table
    thead
      tr
        th
          = Match.human_attribute_name(:host_id)
        th
          = t('.score')
        th
          = Match.human_attribute_name(:guest_id)
        th
          = Match.human_attribute_name(:location)
        th
          = Match.human_attribute_name(:played_at)
        th
          = t('.actions')
    tbody
    
  = link_to t('common.manage.new'), "#new", class: "btn btn-primary"

app/views/templates/matches/_match.html.slim
script#match_template type="text/template"
  td
    <%= get("host").get("name") %>
  td
    <% if (playDate() > new Date()) { %>
      = t('.scheduled')
    <% } else { %>
      <% if (get("host_score") == null || get("guest_score") == null) { %>
        = t('.waiting_results')
      <% } else { %>
        <%= get("host_score") %> 
        | x 
        <%= get("guest_score") %>
      <% } %>
    <% } %>
  td
    <%= get("guest").get("name") %>
  td
    <%= get("location") %>
  td
    <%= get("played_at").substring(0, 10) %>
  td
    .btn-group
      a.btn.btn-small.btn-edit href="#<%= id %>/edit"
        = t('.edit')
      a.btn.btn-small.btn-danger.btn-destroy href="#<%= id %>"
        = t('.destroy')

app/views/templates/matches/_new.html.slim
script#new_match_template type="text/template"
  h1= t('.title')

  .span7
    = form_for :match, html: { class: "soccer-manager-form" } do |f|
      fieldset
        legend= t('.legend.details')
        .control-group.inline-block.padded-right          
          = f.label :host_id
          = f.select :host_id, Club.all.collect { |c| [c.name, c.id] }
        .control-group.inline-block.padded-left
          = f.label :guest_id
          = f.select :guest_id, Club.all.collect { |c| [c.name, c.id] }
        .control-group
          = f.label :location
          = f.text_field :location
        .control-group
          = f.label :played_at
          .input-prepend
            span.add-on
              b.icon-calendar
            = f.text_field :played_at, class: "datepicker input-small", value: "<%= played_at.substring(0,10) %>".html_safe
        .form-actions
          = f.submit class: 'btn btn-primary'
          = link_to t('.back'), '#', class: "btn"

app/views/templates/players/_edit.html.slim
script#edit_player_template type="text/template"
  h1= t('.title')
  = render "templates/players/form"

app/views/templates/players/_form.html.slim
.player-previewer
  table
    tbody
.span7
  = form_for :player, html: { class: "soccer-manager-form" } do |f|
    fieldset
      legend= t('.legend.personal')
      span.help-block
        em
          = t('.helpers.profile_picture')
      .control-group.inline-block.padded-right
        = f.label :first_name
        = f.text_field :first_name, value: "<%= first_name %>".html_safe
      .control-group.inline-block.padded-left
        = f.label :last_name
        = f.text_field :last_name, value: "<%= last_name %>".html_safe
      .control-group
        = f.label :gender
        = f.label :gender_true, class: "radio inline padded-right" do
          <% if ((gender == "true") || gender == true) { %>
            = f.radio_button :gender, "true", checked: "checked"
          <% } else { %>
            = f.radio_button :gender, "true"
          <% } %>
          = t('common.genders.male')
        = f.label :gender_false, class: "radio inline padded-left" do
          <% if (gender == "false" || gender == false) { %>
            = f.radio_button :gender, "false", checked: "checked"
          <% } else { %>
            = f.radio_button :gender, "false"
          <% } %>
          = t('common.genders.female')
      .control-group
        = f.label :born_at
        .input-prepend
          span class="add-on"
            b class="icon-calendar"
          = f.text_field :born_at, class: "datepicker input-small", value: "<%= born_at.substring(0,10) %>".html_safe
      .margin-bottom
    fieldset
      legend= t('.legend.preferences')
      .control-group.inline-block.padded-right
        = f.label :position
        = f.select :position, grouped_options_for_select(Player::POSITIONS)
      .control-group.inline-block.padded-left
        = f.label :number
        = f.number_field :number, class: "input-mini", min: 1, max: 99, value: "<%= number %>".html_safe
    fieldset
      legend= t('.legend.skills')
      .control-group.inline-block.padded-right
        = f.label :acceleration
        = f.number_field :acceleration, class: "input-small", min: 0, max: 10, value: "<%= acceleration %>".html_safe
      .control-group.inline-block.padded-left.padded-right
        = f.label :aggression
        = f.number_field :aggression, class: "input-small", min: 0, max: 10, value: "<%= aggression %>".html_safe
      .control-group.inline-block.padded-left.padded-right
        = f.label :balance
        = f.number_field :balance, class: "input-small", min: 0, max: 10, value: "<%= balance %>".html_safe
      .control-group.inline-block.padded-left.padded-right
        = f.label :marking
        = f.number_field :marking, class: "input-small", min: 0, max: 10, value: "<%= marking %>".html_safe
      .control-group.inline-block.padded-left.padded-right
        = f.label :stamina
        = f.number_field :stamina, class: "input-small", min: 0, max: 10, value: "<%= stamina %>".html_safe
    .form-actions
      = f.submit class: 'btn btn-primary'
      = link_to t('.back'), '#', class: "btn"

app/views/templates/players/_index.html.slim
script#players_template type="text/template"
  h1= t('.title')
  
  table.table.players-table
    thead
      tr
        th.span3
          = Player.human_attribute_name(:name)
        th.span3
          = Player.human_attribute_name(:club)
        th.span1.position
          = Player.human_attribute_name(:position)
        th.span1
          = Player.human_attribute_name(:average)
        th.span1
          = t('common.manage.actions')
    tbody
    
  = link_to t('common.manage.new'), "#new", class: "btn btn-primary"

app/views/templates/players/_new.html.slim
script#new_player_template type="text/template"
  h1= t('.title')
  
  = render "templates/players/form"

app/views/templates/players/_player.html.slim
script#player_template type="text/template"
  td.clickable
    <%= formattedName() %>
  td.clickable
    <%= displayClubName() %>
  td.player-position.clickable
    strong
      <%= displayPosition() %>
  td.clickable
    <%= displayAverage() %>
  td
    .btn-group
      a.btn.btn-small.btn-edit href="#<%= id %>/edit"
        = t('common.manage.edit')
      a.btn.btn-small.btn-danger.btn-destroy href="#<%= id %>"  
        = t('common.manage.destroy')

app/views/templates/players/_show.html.slim
script#show_player_template type="text-template"
  td colspan="5"
    .player-card-container
      .player-card
        .profile.padded
          .picture
            img class="img-polaroid"
          .name
            strong <%= fullName() %>
          .age
            <%= age() %> 
            = t('common.prompts.age')
          .gender
            <%= displayGender() %>
          .club
            <%= displayClubName() %>
          .number
            = "#{t('common.prompts.shirt')} "
            | #<%= get('number') %>
        .skills.padded
          h3= Player.human_attribute_name(:skills)
        .field.padded
          .position
            strong
              <%= get('position') %>

app/views/templates/players/_skills.html.slim
script#player_skills_template type="text/template"
  .skill-name
    em
      <%= name.humanize() %>:
  .skill-value